services:
  - type: web
    name: plant-disease-detection
    runtime: python
    buildCommand: ./build.sh
    startCommand: gunicorn --timeout 300 --workers 1 --threads 1 --worker-class sync --max-requests 1000 --preload app:app
    autoDeploy: true
    envVars:
      - key: SECRET_KEY
        value: your_generated_secret_key_here
      - key: GEMINI_API_KEY
        value: your_api_key_here
      - key: TF_CPP_MIN_LOG_LEVEL
        value: "2"
      - key: PORT
        value: "10000"
    region: oregon
    plan: free
    disk:
      name: uploads_volume
      mountPath: /opt/render/project/src/static/uploads
      sizeGB: 1